name: CI
on:
  push: {}
  #push:
  #  branches:
  #    - master
  pull_request: {}

jobs:
  test-linux:
    name: test-linux
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        #os: [ macos-latest, ubuntu-latest, windows-latest ]
        go: [ ^1.13, ^1.14, ^1.15 ]
        firefox: [ 62.0, 63.0 ]
    runs-on: ${{ matrix.os }}
    env:
      FIREFOX_VERSION: ${{ matrix.firefox }}
    steps:
    - name: Set up golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Instal xvfb headless test
      uses: GabrielBB/xvfb-action@v1

    - name: Get deps and setting up env
      run: |
        go get github.com/axw/gocov/gocov
        go get github.com/mattn/goveralls
        if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
        sh -e /etc/init.d/xvfb start
        sleep 3
        # install firefox
        export FIREFOX_SOURCE_URL="https://download.mozilla.org/?product=firefox-$FIREFOX_VERSION&lang=en-US&os=linux64"
        wget -O /tmp/firefox.tar.bz2 $FIREFOX_SOURCE_URL
        mkdir -p $HOME/firefox
        tar -jvxf /tmp/firefox.tar.bz2 -C $HOME/
        netstat -ptln

        # before run
        $HOME/firefox/firefox --version
        $HOME/firefox/firefox -marionette > /dev/null 2>&1 &
        sleep 30
        netstat -ptln

    - name: Test
      run: go test -test.v -race -coverprofile=coverage.txt -covermode=atomic
